# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TodayWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodayWeather
pod 'Alamofire','4.8.2'
pod 'SwiftyJSON', '5.0.0'
pod 'PKHUD'
end
